# Changes here will be overwritten by Copier
_commit: 5.0.2
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: hyperrealist@pm.me
author_name: hyperrealist
description: Thin Python HTTP client for mlx-kv-server
distribution_name: mlx-kv-client
docker: false
docs_type: sphinx
git_platform: github.com
github_org: distilledecho
package_name: mlx_kv_client
pypi: true
repo_name: mlx-kv-client
strict_typing: true
type_checker: pyright
